[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
	'@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
	'@ensdomains/ens-contracts/=lib/ens-contracts/',
]

optimizer = true
optimizer_runs = 1200
